import { motion } from 'framer-motion';
import { Shield, Sparkles, Lock, HelpCircle } from 'lucide-react';

const AboutPage = () => {
  const faqs = [
    {
      question: "What is a Web3 Wallet Persona?",
      answer: "A Web3 Wallet Persona is a profile generated by analyzing on-chain activity to determine behavioral patterns, preferences, and traits of a wallet owner. It helps understand your on-chain identity and provides insights into your Web3 interactions."
    },
    {
      question: "How is my wallet persona calculated?",
      answer: "Your persona is calculated by analyzing various factors: transaction history, token holdings, NFT collections, DeFi interactions, DAO participation, and more. The system uses these data points to identify patterns and classify your wallet into different personality traits."
    },
    {
      question: "Is my wallet data secure?",
      answer: "Yes, your wallet data is secure. All analysis is performed client-side and we don't store any personal data. We only access publicly available on-chain data that exists on the blockchain."
    },
    {
      question: "What can I do with my wallet persona?",
      answer: "You can use your wallet persona to better understand your on-chain behavior, discover new dApps and projects that align with your interests, share your Web3 identity with others, and get personalized recommendations based on your activity."
    }
  ];

  return (
    <div className="max-w-4xl mx-auto">
      <motion.section 
        className="mb-12"
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5 }}
      >
        <h1 className="text-3xl font-bold mb-6">About Persona</h1>
        <div className="card">
          <p className="text-gray-300 mb-4">
            Persona is a Web3 analytics tool that examines wallet activity to generate a unique 
            on-chain "persona" based on transaction history, asset holdings, and network interactions.
          </p>
          <p className="text-gray-300">
            Whether you're a collector, investor, or active DAO participant, Persona reveals insights 
            about your on-chain behavior and offers personalized recommendations to enhance your Web3 journey.
          </p>
        </div>
      </motion.section>

      <motion.section 
        className="mb-12"
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5, delay: 0.1 }}
      >
        <h2 className="text-2xl font-bold mb-6">Our Methodology</h2>
        
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-6">
          <div className="card">
            <div className="bg-primary-900/50 p-3 rounded-full w-fit mb-4">
              <Sparkles className="h-5 w-5 text-primary-400" />
            </div>
            <h3 className="text-lg font-bold mb-2">Data Analysis</h3>
            <p className="text-gray-400 text-sm">
              We analyze transaction patterns, asset holdings, DeFi interactions, NFT collections, 
              and DAO participation to identify behavioral trends.
            </p>
          </div>
          
          <div className="card">
            <div className="bg-secondary-900/50 p-3 rounded-full w-fit mb-4">
              <Lock className="h-5 w-5 text-secondary-400" />
            </div>
            <h3 className="text-lg font-bold mb-2">Pattern Recognition</h3>
            <p className="text-gray-400 text-sm">
              Our algorithm identifies patterns in your on-chain activity to classify your wallet 
              into different persona types based on your most common behaviors.
            </p>
          </div>
          
          <div className="card">
            <div className="bg-accent-900/50 p-3 rounded-full w-fit mb-4">
              <Shield className="h-5 w-5 text-accent-400" />
            </div>
            <h3 className="text-lg font-bold mb-2">Trait Mapping</h3>
            <p className="text-gray-400 text-sm">
              We map identified patterns to personality traits, creating a comprehensive profile 
              that reflects your Web3 identity and preferences.
            </p>
          </div>
        </div>
      </motion.section>

      <motion.section 
        className="mb-12"
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5, delay: 0.2 }}
      >
        <h2 className="text-2xl font-bold mb-6">Frequently Asked Questions</h2>
        
        <div className="space-y-4">
          {faqs.map((faq, index) => (
            <motion.div 
              key={index} 
              className="card"
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.3, delay: 0.3 + index * 0.1 }}
            >
              <div className="flex items-start">
                <div className="mt-1 mr-3">
                  <HelpCircle className="h-5 w-5 text-primary-400" />
                </div>
                <div>
                  <h3 className="text-lg font-medium mb-2">{faq.question}</h3>
                  <p className="text-gray-400">{faq.answer}</p>
                </div>
              </div>
            </motion.div>
          ))}
        </div>
      </motion.section>

      <motion.section 
        className="mb-12"
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5, delay: 0.3 }}
      >
        <div className="card bg-gradient-to-br from-primary-900/50 to-secondary-900/50 border border-gray-800">
          <div className="text-center">
            <h2 className="text-2xl font-bold mb-4">Try It Now</h2>
            <p className="text-gray-300 mb-6">
              Discover what your wallet activity reveals about your Web3 persona.
            </p>
            <a href="/" className="btn-primary inline-flex items-center">
              Analyze Your Wallet
            </a>
          </div>
        </div>
      </motion.section>
    </div>
  );
};

export default AboutPage;